'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.RadScheduler
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Main
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RadScheduler.Main", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to After.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedAfter() As String
            Get
                Return ResourceManager.GetString("AdvancedAfter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Celý den.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedAllDayEvent() As String
            Get
                Return ResourceManager.GetString("AdvancedAllDayEvent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedCalendarCancel() As String
            Get
                Return ResourceManager.GetString("AdvancedCalendarCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedCalendarOK() As String
            Get
                Return ResourceManager.GetString("AdvancedCalendarOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dnes.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedCalendarToday() As String
            Get
                Return ResourceManager.GetString("AdvancedCalendarToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedClose() As String
            Get
                Return ResourceManager.GetString("AdvancedClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Daily.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDaily() As String
            Get
                Return ResourceManager.GetString("AdvancedDaily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Den.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDay() As String
            Get
                Return ResourceManager.GetString("AdvancedDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Day of the month.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDayOfMonth() As String
            Get
                Return ResourceManager.GetString("AdvancedDayOfMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Day of the week.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDayOfWeek() As String
            Get
                Return ResourceManager.GetString("AdvancedDayOfWeek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to day(s).
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDays() As String
            Get
                Return ResourceManager.GetString("AdvancedDays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Popis.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDescription() As String
            Get
                Return ResourceManager.GetString("AdvancedDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Done.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedDone() As String
            Get
                Return ResourceManager.GetString("AdvancedDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Appointment.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEditAppointment() As String
            Get
                Return ResourceManager.GetString("AdvancedEditAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End after.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEndAfter() As String
            Get
                Return ResourceManager.GetString("AdvancedEndAfter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End by.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEndByThisDate() As String
            Get
                Return ResourceManager.GetString("AdvancedEndByThisDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End date is required.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEndDateRequired() As String
            Get
                Return ResourceManager.GetString("AdvancedEndDateRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End time is required.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEndTimeRequired() As String
            Get
                Return ResourceManager.GetString("AdvancedEndTimeRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Every.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEvery() As String
            Get
                Return ResourceManager.GetString("AdvancedEvery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Every weekday.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEveryWeekday() As String
            Get
                Return ResourceManager.GetString("AdvancedEveryWeekday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Every working day.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedEveryWorkingDay() As String
            Get
                Return ResourceManager.GetString("AdvancedEveryWorkingDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to první.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedFirst() As String
            Get
                Return ResourceManager.GetString("AdvancedFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fourth.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedFourth() As String
            Get
                Return ResourceManager.GetString("AdvancedFourth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start time.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedFrom() As String
            Get
                Return ResourceManager.GetString("AdvancedFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hourly.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedHourly() As String
            Get
                Return ResourceManager.GetString("AdvancedHourly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hour(s).
        '''</summary>
        Friend Shared ReadOnly Property AdvancedHours() As String
            Get
                Return ResourceManager.GetString("AdvancedHours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid number.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedInvalidNumber() As String
            Get
                Return ResourceManager.GetString("AdvancedInvalidNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poslední.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedLast() As String
            Get
                Return ResourceManager.GetString("AdvancedLast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to den.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMaskDay() As String
            Get
                Return ResourceManager.GetString("AdvancedMaskDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to weekday.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMaskWeekday() As String
            Get
                Return ResourceManager.GetString("AdvancedMaskWeekday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to weekend day.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMaskWeekendDay() As String
            Get
                Return ResourceManager.GetString("AdvancedMaskWeekendDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monthly.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMonthly() As String
            Get
                Return ResourceManager.GetString("AdvancedMonthly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to month(s).
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMonths() As String
            Get
                Return ResourceManager.GetString("AdvancedMonths", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to More details.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedMoreDetails() As String
            Get
                Return ResourceManager.GetString("AdvancedMoreDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Never.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedNever() As String
            Get
                Return ResourceManager.GetString("AdvancedNever", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Appointment.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedNewAppointment() As String
            Get
                Return ResourceManager.GetString("AdvancedNewAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No end date.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedNoEndDate() As String
            Get
                Return ResourceManager.GetString("AdvancedNoEndDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to occurrences.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedOccurrences() As String
            Get
                Return ResourceManager.GetString("AdvancedOccurrences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to of.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedOf() As String
            Get
                Return ResourceManager.GetString("AdvancedOf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to of every.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedOfEvery() As String
            Get
                Return ResourceManager.GetString("AdvancedOfEvery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedOn() As String
            Get
                Return ResourceManager.GetString("AdvancedOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Range of recurrence:.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRange() As String
            Get
                Return ResourceManager.GetString("AdvancedRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recur every.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRecurEvery() As String
            Get
                Return ResourceManager.GetString("AdvancedRecurEvery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recurrence.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRecurrence() As String
            Get
                Return ResourceManager.GetString("AdvancedRecurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recurring task.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRecurringAppointment() As String
            Get
                Return ResourceManager.GetString("AdvancedRecurringAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repeat.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRepeat() As String
            Get
                Return ResourceManager.GetString("AdvancedRepeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repeat Appointment.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRepeatAppointment() As String
            Get
                Return ResourceManager.GetString("AdvancedRepeatAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repeat End.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRepeatEnd() As String
            Get
                Return ResourceManager.GetString("AdvancedRepeatEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repeat On.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedRepeatOn() As String
            Get
                Return ResourceManager.GetString("AdvancedRepeatOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to reset exceptions.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedReset() As String
            Get
                Return ResourceManager.GetString("AdvancedReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to druhý.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedSecond() As String
            Get
                Return ResourceManager.GetString("AdvancedSecond", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start date is required.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedStartDateRequired() As String
            Get
                Return ResourceManager.GetString("AdvancedStartDateRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start time must be before end time.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedStartTimeBeforeEndTime() As String
            Get
                Return ResourceManager.GetString("AdvancedStartTimeBeforeEndTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start time is required.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedStartTimeRequired() As String
            Get
                Return ResourceManager.GetString("AdvancedStartTimeRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subject.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedSubject() As String
            Get
                Return ResourceManager.GetString("AdvancedSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please provide appointment subject.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedSubjectRequired() As String
            Get
                Return ResourceManager.GetString("AdvancedSubjectRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedThe() As String
            Get
                Return ResourceManager.GetString("AdvancedThe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to třetí.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedThird() As String
            Get
                Return ResourceManager.GetString("AdvancedThird", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time zone.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedTimeZone() As String
            Get
                Return ResourceManager.GetString("AdvancedTimeZone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Konec.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedTo() As String
            Get
                Return ResourceManager.GetString("AdvancedTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weekly.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedWeekly() As String
            Get
                Return ResourceManager.GetString("AdvancedWeekly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to week(s) on.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedWeeks() As String
            Get
                Return ResourceManager.GetString("AdvancedWeeks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Working....
        '''</summary>
        Friend Shared ReadOnly Property AdvancedWorking() As String
            Get
                Return ResourceManager.GetString("AdvancedWorking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yearly.
        '''</summary>
        Friend Shared ReadOnly Property AdvancedYearly() As String
            Get
                Return ResourceManager.GetString("AdvancedYearly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to year(s).
        '''</summary>
        Friend Shared ReadOnly Property AdvancedYears() As String
            Get
                Return ResourceManager.GetString("AdvancedYears", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to celý den.
        '''</summary>
        Friend Shared ReadOnly Property AllDay() As String
            Get
                Return ResourceManager.GetString("AllDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmCancel() As String
            Get
                Return ResourceManager.GetString("ConfirmCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete this appointment?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmDeleteText() As String
            Get
                Return ResourceManager.GetString("ConfirmDeleteText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm delete.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmDeleteTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmOK() As String
            Get
                Return ResourceManager.GetString("ConfirmOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete only this occurrence..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceDeleteOccurrence() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceDeleteOccurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete the series..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceDeleteSeries() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceDeleteSeries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deleting a recurring appointment.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceDeleteTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceDeleteTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit only this occurrence..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceEditOccurrence() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceEditOccurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit the series..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceEditSeries() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceEditSeries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editing a recurring appointment.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceEditTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceEditTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Move only this occurrence..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceMoveOccurrence() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceMoveOccurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Move the series..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceMoveSeries() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceMoveSeries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Moving a recurring appointment.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceMoveTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceMoveTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resize only this occurrence..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceResizeOccurrence() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceResizeOccurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resize the series..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceResizeSeries() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceResizeSeries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resizing a recurring appointment.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmRecurrenceResizeTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmRecurrenceResizeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to delete all existing recurrence exceptions?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmResetExceptionsText() As String
            Get
                Return ResourceManager.GetString("ConfirmResetExceptionsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm reset exceptions.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmResetExceptionsTitle() As String
            Get
                Return ResourceManager.GetString("ConfirmResetExceptionsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Appointment.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuAddAppointment() As String
            Get
                Return ResourceManager.GetString("ContextMenuAddAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Recurring Appointment.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuAddRecurringAppointment() As String
            Get
                Return ResourceManager.GetString("ContextMenuAddRecurringAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuDelete() As String
            Get
                Return ResourceManager.GetString("ContextMenuDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuEdit() As String
            Get
                Return ResourceManager.GetString("ContextMenuEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jít na dnes.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuGoToToday() As String
            Get
                Return ResourceManager.GetString("ContextMenuGoToToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Událost.
        '''</summary>
        Friend Shared ReadOnly Property HeaderAgendaAppointment() As String
            Get
                Return ResourceManager.GetString("HeaderAgendaAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Čas.
        '''</summary>
        Friend Shared ReadOnly Property HeaderAgendaTime() As String
            Get
                Return ResourceManager.GetString("HeaderAgendaTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Den.
        '''</summary>
        Friend Shared ReadOnly Property HeaderDay() As String
            Get
                Return ResourceManager.GetString("HeaderDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Měsíc.
        '''</summary>
        Friend Shared ReadOnly Property HeaderMonth() As String
            Get
                Return ResourceManager.GetString("HeaderMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-den.
        '''</summary>
        Friend Shared ReadOnly Property HeaderMultiDay() As String
            Get
                Return ResourceManager.GetString("HeaderMultiDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to další den.
        '''</summary>
        Friend Shared ReadOnly Property HeaderNextDay() As String
            Get
                Return ResourceManager.GetString("HeaderNextDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to předchozí den.
        '''</summary>
        Friend Shared ReadOnly Property HeaderPrevDay() As String
            Get
                Return ResourceManager.GetString("HeaderPrevDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timeline.
        '''</summary>
        Friend Shared ReadOnly Property HeaderTimeline() As String
            Get
                Return ResourceManager.GetString("HeaderTimeline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dnes.
        '''</summary>
        Friend Shared ReadOnly Property HeaderToday() As String
            Get
                Return ResourceManager.GetString("HeaderToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Týden.
        '''</summary>
        Friend Shared ReadOnly Property HeaderWeek() As String
            Get
                Return ResourceManager.GetString("HeaderWeek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reminder.
        '''</summary>
        Friend Shared ReadOnly Property Reminder() As String
            Get
                Return ResourceManager.GetString("Reminder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to before start.
        '''</summary>
        Friend Shared ReadOnly Property ReminderBeforeStart() As String
            Get
                Return ResourceManager.GetString("ReminderBeforeStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to day.
        '''</summary>
        Friend Shared ReadOnly Property ReminderDay() As String
            Get
                Return ResourceManager.GetString("ReminderDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to days.
        '''</summary>
        Friend Shared ReadOnly Property ReminderDays() As String
            Get
                Return ResourceManager.GetString("ReminderDays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dismiss.
        '''</summary>
        Friend Shared ReadOnly Property ReminderDismiss() As String
            Get
                Return ResourceManager.GetString("ReminderDismiss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dismiss All.
        '''</summary>
        Friend Shared ReadOnly Property ReminderDismissAll() As String
            Get
                Return ResourceManager.GetString("ReminderDismissAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to due in.
        '''</summary>
        Friend Shared ReadOnly Property ReminderDueIn() As String
            Get
                Return ResourceManager.GetString("ReminderDueIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hour.
        '''</summary>
        Friend Shared ReadOnly Property ReminderHour() As String
            Get
                Return ResourceManager.GetString("ReminderHour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hours.
        '''</summary>
        Friend Shared ReadOnly Property ReminderHours() As String
            Get
                Return ResourceManager.GetString("ReminderHours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minute.
        '''</summary>
        Friend Shared ReadOnly Property ReminderMinute() As String
            Get
                Return ResourceManager.GetString("ReminderMinute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minutes.
        '''</summary>
        Friend Shared ReadOnly Property ReminderMinutes() As String
            Get
                Return ResourceManager.GetString("ReminderMinutes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend Shared ReadOnly Property ReminderNone() As String
            Get
                Return ResourceManager.GetString("ReminderNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Item.
        '''</summary>
        Friend Shared ReadOnly Property ReminderOpenItem() As String
            Get
                Return ResourceManager.GetString("ReminderOpenItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to overdue.
        '''</summary>
        Friend Shared ReadOnly Property ReminderOverdue() As String
            Get
                Return ResourceManager.GetString("ReminderOverdue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reminders.
        '''</summary>
        Friend Shared ReadOnly Property Reminders() As String
            Get
                Return ResourceManager.GetString("Reminders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Snooze.
        '''</summary>
        Friend Shared ReadOnly Property ReminderSnooze() As String
            Get
                Return ResourceManager.GetString("ReminderSnooze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click Snooze to be reminded again in:.
        '''</summary>
        Friend Shared ReadOnly Property ReminderSnoozeHint() As String
            Get
                Return ResourceManager.GetString("ReminderSnoozeHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to week.
        '''</summary>
        Friend Shared ReadOnly Property ReminderWeek() As String
            Get
                Return ResourceManager.GetString("ReminderWeek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to weeks.
        '''</summary>
        Friend Shared ReadOnly Property ReminderWeeks() As String
            Get
                Return ResourceManager.GetString("ReminderWeeks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please do not remove this key..
        '''</summary>
        Friend Shared ReadOnly Property ReservedResource() As String
            Get
                Return ResourceManager.GetString("ReservedResource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show 24 hours....
        '''</summary>
        Friend Shared ReadOnly Property Show24Hours() As String
            Get
                Return ResourceManager.GetString("Show24Hours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend Shared ReadOnly Property ShowAdvancedForm() As String
            Get
                Return ResourceManager.GetString("ShowAdvancedForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show business hours....
        '''</summary>
        Friend Shared ReadOnly Property ShowBusinessHours() As String
            Get
                Return ResourceManager.GetString("ShowBusinessHours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to více....
        '''</summary>
        Friend Shared ReadOnly Property ShowMore() As String
            Get
                Return ResourceManager.GetString("ShowMore", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
