'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class sys_dbobjects

    '''<summary>
    '''imgFormHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFormHeader As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblFormHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdRecalcTrees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRecalcTrees As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtTreeTables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTreeTables As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdGenerate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGenerate1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdGenerate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGenerate2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdGenerateXmlDistributionFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGenerateXmlDistributionFiles As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtDatabaseSourceForXmlDistribution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDatabaseSourceForXmlDistribution As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdGenerate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGenerate3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtCompareCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompareCon As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdBackup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdBackup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDump control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDump As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''chkIncludeGO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeGO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDUMPDef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDUMPDef As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDUMPResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDUMPResult As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdNoIdentity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdNoIdentity As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''chkUseCompareCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseCompareCon As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.Site
        Get
            Return CType(MyBase.Master, UI.Site)
        End Get
    End Property
End Class
