if exists (select 1 from sysobjects where  id = object_id('p31_setup_temp') and type = 'P')
 drop procedure p31_setup_temp
GO






CREATE procedure [dbo].[p31_setup_temp]
@p31id int	---p31id
,@guid varchar(50)
AS

if exists(select p31ID FROM p31Worksheet_Temp WHERE p31GUID=@guid AND p31ID=@p31id)
 return ---temp data se na úvod plní pouze jednou

INSERT INTO p31Worksheet_Temp
(
[p31GUID]
	  ,[p31ID]
      ,[p41ID]
      ,[j02ID]
      ,[p32ID]
      ,[p56ID]
      ,[j02ID_Owner]
      ,[j02ID_ApprovedBy]
      ,[p31Code]
      ,[p70ID]
      ,[p71ID]
      ,[p72ID_AfterApprove]
      ,[p72ID_AfterTrimming]
      ,[j27ID_Billing_Orig]
      ,[j27ID_Billing_Invoiced]
      ,[j27ID_Billing_Invoiced_Domestic]
      ,[j27ID_Internal]
      ,[p91ID]
      ,[c11ID]
      ,[p31Date]
      ,[p31DateUntil]
      ,[p31HoursEntryFlag]
      ,[p31Approved_When]
      ,[p31IsPlanRecord]
      ,[p31Text]
      ,[p31Value_Orig]
      ,[p31Value_Trimmed]
      ,[p31Value_Approved_Billing]
      ,[p31Value_Approved_Internal]
      ,[p31Value_Invoiced]
      ,[p31Amount_WithoutVat_Orig]
      ,[p31Amount_WithVat_Orig]
      ,[p31Amount_Vat_Orig]
      ,[p31VatRate_Orig]
      ,[p31Amount_WithoutVat_FixedCurrency]
      ,[p31Amount_WithoutVat_Invoiced]
      ,[p31Amount_WithVat_Invoiced]
      ,[p31Amount_Vat_Invoiced]
      ,[p31VatRate_Invoiced]
      ,[p31Amount_WithoutVat_Invoiced_Domestic]
      ,[p31Amount_WithVat_Invoiced_Domestic]
      ,[p31Amount_Vat_Invoiced_Domestic]
      ,[p31Minutes_Orig]
      ,[p31Minutes_Trimmed]
      ,[p31Minutes_Approved_Billing]
      ,[p31Minutes_Approved_Internal]
      ,[p31Minutes_Invoiced]
      ,[p31HHMM_Orig]
      ,[p31HHMM_Trimmed]
      ,[p31HHMM_Approved_Billing]
      ,[p31HHMM_Approved_Internal]
      ,[p31HHMM_Invoiced]
      ,[p31Rate_Billing_Orig]
      ,[p31Rate_Internal_Orig]
      ,[p31Rate_Billing_Approved]
      ,[p31Rate_Internal_Approved]
      ,[p31Rate_Billing_Invoiced]
      ,[p31Amount_WithoutVat_Approved]
      ,[p31Amount_WithVat_Approved]
      ,[p31Amount_Vat_Approved]
      ,[p31VatRate_Approved]
      ,[p31Amount_Internal]
      ,[p31Amount_Internal_Approved]
      ,[p31ExchangeRate_Domestic]
      ,[p31ExchangeRate_Invoice]
      ,[p31DateTimeFrom_Orig]
      ,[p31DateTimeUntil_Orig]
      ,[p31Value_Orig_Entried]
      ,[p31DateInsert]
      ,[p31UserInsert]
      ,[p31DateUpdate]
      ,[p31UserUpdate]
      ,[p31ValidFrom]
      ,[p31ValidUntil]
	  ,[p31Hours_Orig]
      ,[p31Hours_Trimmed]
      ,[p31Hours_Approved_Billing]
      ,[p31Hours_Approved_Internal]
      ,[p31Hours_Invoiced]
)
SELECT @guid
	  ,[p31ID]
      ,[p41ID]
      ,[j02ID]
      ,[p32ID]
      ,[p56ID]
      ,[j02ID_Owner]
      ,[j02ID_ApprovedBy]
      ,[p31Code]
      ,[p70ID]
      ,[p71ID]
      ,[p72ID_AfterApprove]
      ,[p72ID_AfterTrimming]
      ,[j27ID_Billing_Orig]
      ,[j27ID_Billing_Invoiced]
      ,[j27ID_Billing_Invoiced_Domestic]
      ,[j27ID_Internal]
      ,[p91ID]
      ,[c11ID]
      ,[p31Date]
      ,[p31DateUntil]
      ,[p31HoursEntryFlag]
      ,[p31Approved_When]
      ,[p31IsPlanRecord]
      ,[p31Text]
      ,[p31Value_Orig]
      ,[p31Value_Trimmed]
      ,[p31Value_Approved_Billing]
      ,[p31Value_Approved_Internal]
      ,[p31Value_Invoiced]
      ,[p31Amount_WithoutVat_Orig]
      ,[p31Amount_WithVat_Orig]
      ,[p31Amount_Vat_Orig]
      ,[p31VatRate_Orig]
      ,[p31Amount_WithoutVat_FixedCurrency]
      ,[p31Amount_WithoutVat_Invoiced]
      ,[p31Amount_WithVat_Invoiced]
      ,[p31Amount_Vat_Invoiced]
      ,[p31VatRate_Invoiced]
      ,[p31Amount_WithoutVat_Invoiced_Domestic]
      ,[p31Amount_WithVat_Invoiced_Domestic]
      ,[p31Amount_Vat_Invoiced_Domestic]
      ,[p31Minutes_Orig]
      ,[p31Minutes_Trimmed]
      ,[p31Minutes_Approved_Billing]
      ,[p31Minutes_Approved_Internal]
      ,[p31Minutes_Invoiced]
      ,[p31HHMM_Orig]
      ,[p31HHMM_Trimmed]
      ,[p31HHMM_Approved_Billing]
      ,[p31HHMM_Approved_Internal]
      ,[p31HHMM_Invoiced]
      ,[p31Rate_Billing_Orig]
      ,[p31Rate_Internal_Orig]
      ,[p31Rate_Billing_Approved]
      ,[p31Rate_Internal_Approved]
      ,[p31Rate_Billing_Invoiced]
      ,[p31Amount_WithoutVat_Approved]
      ,[p31Amount_WithVat_Approved]
      ,[p31Amount_Vat_Approved]
      ,[p31VatRate_Approved]
      ,[p31Amount_Internal]
      ,[p31Amount_Internal_Approved]
      ,[p31ExchangeRate_Domestic]
      ,[p31ExchangeRate_Invoice]
      ,[p31DateTimeFrom_Orig]
      ,[p31DateTimeUntil_Orig]
      ,[p31Value_Orig_Entried]
      ,[p31DateInsert]
      ,[p31UserInsert]
      ,[p31DateUpdate]
      ,[p31UserUpdate]
      ,[p31ValidFrom]
      ,[p31ValidUntil]
	  ,[p31Hours_Orig]
      ,[p31Hours_Trimmed]
      ,[p31Hours_Approved_Billing]
      ,[p31Hours_Approved_Internal]
      ,[p31Hours_Invoiced]
  FROM [dbo].[p31Worksheet]
  WHERE p31ID=@p31id

GO