'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_robot

    '''<summary>
    '''chkUseRobot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseRobot As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''panRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panRec As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblrobot_host control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrobot_host As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''robot_host control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents robot_host As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblHostHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHostHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblrobot_cache_timeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrobot_cache_timeout As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''robot_cache_timeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents robot_cache_timeout As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.ModalForm
        Get
            Return CType(MyBase.Master, UI.ModalForm)
        End Get
    End Property
End Class
