'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class clue_p42_record

    '''<summary>
    '''ph1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ph1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panModules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panModules As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''p42IsModule_p31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p42IsModule_p31 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''p42IsModule_p56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p42IsModule_p56 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''p42IsModule_o22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p42IsModule_o22 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''p42IsModule_o23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p42IsModule_o23 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''p42IsModule_p45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p42IsModule_p45 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''p42IsModule_p48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p42IsModule_p48 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''panP34IDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panP34IDs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rpP34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpP34 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.Clue
        Get
            Return CType(MyBase.Master, UI.Clue)
        End Get
    End Property
End Class
