'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class mobile_p91_framework

    '''<summary>
    '''RecordHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecordHeader As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''liP41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liP41 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CountP41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountP41 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''liP31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liP31 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CountP31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountP31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdReportInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdReportInvoice As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''cmdReportAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdReportAttachment As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''p91Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p91Code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgDraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDraft As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''p92Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p92Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trB02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trB02 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''b02Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b02Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Client As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''p91Amount_Debt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p91Amount_Debt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p91Amount_WithoutVat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p91Amount_WithoutVat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p91Amount_Vat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p91Amount_Vat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p91Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p91Date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p91DateSupply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p91DateSupply As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p91DateMaturity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p91DateMaturity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p91Text1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p91Text1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''boxX18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxX18 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CountX18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountX18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''labels1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labels1 As Global.UI.x18_readonly

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.Mobile
        Get
            Return CType(MyBase.Master, UI.Mobile)
        End Get
    End Property
End Class
