'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class o23_queue

    '''<summary>
    '''EntityName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EntityRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''img1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''x18Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x18Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVirtualCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVirtualCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbxMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbxPeriodType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxPeriodType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''period1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents period1 As Global.UI.periodcombo

    '''<summary>
    '''panWorkflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panWorkflow As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cbxQueryB02ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxQueryB02ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CurrentPeriodQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentPeriodQuery As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CurrentQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentQuery As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdCĺearFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCĺearFilter As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''grid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid1 As Global.UI.datagrid

    '''<summary>
    '''hidX18ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidX18ID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidX20ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidX20ID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidMasterPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMasterPrefix As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidMasterPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMasterPID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddatapid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddatapid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidB01ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidB01ID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidx18GridColsFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidx18GridColsFlag As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidCols control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCols As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidX23ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidX23ID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidDefaultSorting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDefaultSorting As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cmdDoubleClick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDoubleClick As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.ModalForm
        Get
            Return CType(MyBase.Master, UI.ModalForm)
        End Get
    End Property
End Class
