'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class p31_setting

    '''<summary>
    '''panT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panT As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''opgHoursEntryFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opgHoursEntryFlag As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''p31_PreFillP32ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p31_PreFillP32ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowTimeInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowTimeInterval As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''p31_HoursInputInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p31_HoursInputInterval As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''p31_HoursInputFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p31_HoursInputFormat As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''p31_TimeInputInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p31_TimeInputInterval As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''p31_TimeInput_Start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p31_TimeInput_Start As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''p31_TimeInput_End control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p31_TimeInput_End As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.ModalForm
        Get
            Return CType(MyBase.Master, UI.ModalForm)
        End Get
    End Property
End Class
