'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class p40_record

    '''<summary>
    '''lblP40Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblP40Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p40name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p40name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblJ02ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJ02ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j02ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j02ID As Global.UI.person

    '''<summary>
    '''lblP34ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblP34ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p34ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p34ID As Global.UI.datacombo

    '''<summary>
    '''lblP32ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblP32ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p32ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p32ID As Global.UI.datacombo

    '''<summary>
    '''lblJ27ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJ27ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j27ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j27ID As Global.UI.datacombo

    '''<summary>
    '''lblX15ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblX15ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x15ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x15ID As Global.UI.datacombo

    '''<summary>
    '''lblP40Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblP40Value As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p40Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p40Value As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''opgGenType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opgGenType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''panTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panTask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblP56ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblP56ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p56ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p56ID As Global.UI.datacombo

    '''<summary>
    '''panDateSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panDateSettings As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblp40FirstSupplyDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblp40FirstSupplyDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p40FirstSupplyDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p40FirstSupplyDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''lblp40LastSupplyDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblp40LastSupplyDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p40LastSupplyDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p40LastSupplyDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''p40RecurrenceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p40RecurrenceType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblp40GenerateDayAfterSupply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblp40GenerateDayAfterSupply As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p40GenerateDayAfterSupply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p40GenerateDayAfterSupply As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''SharedCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SharedCalendar As Global.Telerik.Web.UI.RadCalendar

    '''<summary>
    '''lblp40Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblp40Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p40Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p40Text As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hidP41ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidP41ID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.ModalDataRecord
        Get
            Return CType(MyBase.Master, UI.ModalDataRecord)
        End Get
    End Property
End Class
