'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class p41_framework_detail

    '''<summary>
    '''menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu1 As Global.UI.entity_menu

    '''<summary>
    '''imgRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRecord As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''boxCoreTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxCoreTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgFavourite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFavourite As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Project control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Project As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgFlag_Project control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFlag_Project As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgDraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDraft As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panDraftCommands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panDraftCommands As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pmClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pmClient As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Client As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''clue_client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clue_client As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''imgFlag_Client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFlag_Client As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblClientBilling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientBilling As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ClientBilling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientBilling As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''trWorkflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trWorkflow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblB02ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblB02ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''b02Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b02Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdWorkflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdWorkflow As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''trPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPlan As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PlanPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlanPeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''aP48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aP48 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''trP51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trP51 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblX51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblX51 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p51Name_Billing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p51Name_Billing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''clue_p51id_billing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clue_p51id_billing As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblX51_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblX51_Message As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblP42Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblP42Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p42Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p42Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''clue_p42name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clue_p42name As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblJ18Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJ18Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j18Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j18Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''clue_j18name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clue_j18name As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblP61Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblP61Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p61Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p61Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''clue_p61Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clue_p61Name As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Owner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Owner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linkTimestamp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkTimestamp As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''tags1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tags1 As Global.UI.mytags

    '''<summary>
    '''folder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folder1 As Global.UI.f01folder

    '''<summary>
    '''tree1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tree1 As Global.UI.TreeMenu

    '''<summary>
    '''linkBatchUpdateChilds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkBatchUpdateChilds As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''boxP40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP40 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxP40Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP40Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rpP40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpP40 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''boxP30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP30 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxP30Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP30Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdEditP30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEditP30 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''persons1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents persons1 As Global.UI.contactpersons

    '''<summary>
    '''boxFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxFF As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxFFTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxFFTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkFFShowFilledOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFFShowFilledOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ff1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ff1 As Global.UI.freefields_readonly

    '''<summary>
    '''boxRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxRoles As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxRolesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxRolesTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''roles_project control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents roles_project As Global.UI.entityrole_assign_inline

    '''<summary>
    '''boxP64 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP64 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxP64Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP64Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rpP64 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpP64 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''boxBillingMemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxBillingMemo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''p41BillingMemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p41BillingMemo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panRecurrence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panRecurrence As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RecurrenceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecurrenceType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p41RecurNameMask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p41RecurNameMask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p41RecurBaseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p41RecurBaseDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LastChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastChild As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblNextGen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextGen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''alert1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alert1 As Global.UI.alertbox

    '''<summary>
    '''cal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal1 As Global.UI.myscheduler

    '''<summary>
    '''boxX18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxX18 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''labels1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labels1 As Global.UI.x18_readonly

    '''<summary>
    '''comments1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comments1 As Global.UI.b07_list

    '''<summary>
    '''boxP31Summary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP31Summary As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxP31SummaryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP31SummaryTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p31summary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p31summary1 As Global.UI.entity_worksheet_summary

    '''<summary>
    '''linkLastInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkLastInvoice As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Last_WIP_Worksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Last_WIP_Worksheet As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdConvertDraft2Normal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConvertDraft2Normal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hidCal1ShallBeActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCal1ShallBeActive As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.SubForm
        Get
            Return CType(MyBase.Master, UI.SubForm)
        End Get
    End Property
End Class
