'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class p45_vysledovka

    '''<summary>
    '''total_costfee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents total_costfee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''total_billingfee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents total_billingfee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''result_t control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents result_t As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''total_expense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents total_expense As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''total_income control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents total_income As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''result_m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents result_m As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''total_cost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents total_cost As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''total_billing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents total_billing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''result_lost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents result_lost As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''result_profit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents result_profit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgEmotion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEmotion As Global.System.Web.UI.WebControls.Image
End Class
