'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class x28_record

    '''<summary>
    '''lblX29ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblX29ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x29ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x29ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''x28Flag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28Flag As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x24id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x24id As Global.UI.datacombo

    '''<summary>
    '''tabFlag1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabFlag1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x23ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x23ID As Global.UI.datacombo

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x27ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x27ID As Global.UI.datacombo

    '''<summary>
    '''x28IsRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28IsRequired As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblx28TextboxWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblx28TextboxWidth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28TextboxWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28TextboxWidth As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''lblx28TextboxHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblx28TextboxHeight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28TextboxHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28TextboxHeight As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''lblx28DataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblx28DataSource As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28DataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28DataSource As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblItemsListDelimiter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItemsListDelimiter As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28IsFixedDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28IsFixedDataSource As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28Ordinary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28Ordinary As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''lblx28field control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblx28field As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28field control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28field As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tabFlag2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabFlag2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblx28Grid_Field control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblx28Grid_Field As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28Grid_Field control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28Grid_Field As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblx28Grid_SqlSyntax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblx28Grid_SqlSyntax As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28Grid_SqlSyntax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28Grid_SqlSyntax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblx28Grid_SqlFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblx28Grid_SqlFrom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28Grid_SqlFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28Grid_SqlFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblx28Query_Field control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblx28Query_Field As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28Query_Field control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28Query_Field As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblx28Query_SqlSyntax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblx28Query_SqlSyntax As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28Query_SqlSyntax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28Query_SqlSyntax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tabPivot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabPivot As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28Pivot_SelectSql control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28Pivot_SelectSql As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x28Pivot_GroupBySql control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28Pivot_GroupBySql As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''x28IsPublic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28IsPublic As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''panPublic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panPublic As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''x28NotPublic_j04IDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28NotPublic_j04IDs As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''x28NotPublic_j07IDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28NotPublic_j07IDs As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''x28IsAllEntityTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28IsAllEntityTypes As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''panEntityTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panEntityTypes As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rp1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''panHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panHelp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''x28HelpText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x28HelpText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.ModalDataRecord
        Get
            Return CType(MyBase.Master, UI.ModalDataRecord)
        End Get
    End Property
End Class
